### ISSUE TITLE
Cannot  import nlpnet - ImportError: cannot import name 'utils'

### ISSUE THREAD

**Issue by GraphGrail** [erickrf/nlpnet#22]
I converted nlpnet to python 3 using standart 2to3 tool, installed successfuly.
Now try to import, but error:
```

>>> import nlpnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/nlpnet/__init__.py", line 3, in <module>
    from . import taggers
  File "/usr/local/lib/python3.4/dist-packages/nlpnet/taggers.py", line 11, in <module>
    from . import utils
ImportError: cannot import name 'utils'
```

**Comment by girishramnani** [comment]
if solved then close this issue
