### ISSUE TITLE
Invalid data directory

### ISSUE THREAD

**Issue by JafferWilson** [erickrf/nlpnet#35]
I am trying to run your repository and getting the following issue:
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nlpnet/taggers.py", line 307, in __init__
    super(DependencyParser, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nlpnet/taggers.py", line 190, in __init__
    self.paths = config.get_config_paths(data_dir)
  File "/usr/local/lib/python2.7/dist-packages/nlpnet/config.py", line 14, in get_config_paths
    assert os.path.isdir(directory), 'Invalid data directory'
AssertionError: Invalid data directory

```
Please help me soon. I am in a bit urgency.

**Comment by erickrf** [comment]
You closed the issue... did you find the solution?
You are probably supplying an invalid data directory when calling the model.

**Comment by JafferWilson** [comment]
Yes, I got it...
Actually, I was a bit confused with the dependency folder. But later on when I read your READ.ME file then I came to know where I need to get it.
But anyways, thank you for your consideration. I am glad that you replied.
