### ISSUE TITLE
"can't multiply sequence" when SRLTagger

### ISSUE THREAD

**Issue by biihberduugo** [erickrf/nlpnet#43]
I just run the test code and had that error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/nlpnet/taggers.py", line 205, in __init__
    self._load_data()
  File "/usr/local/lib/python3.5/dist-packages/nlpnet/taggers.py", line 224, in _load_data
    self.boundary_nn = load_network(md_boundary)
  File "/usr/local/lib/python3.5/dist-packages/nlpnet/taggers.py", line 38, in load_network
    nn = net_class.load_from_file(md.paths[md.network])
  File "networkconv.pyx", line 245, in nlpnet.network.ConvolutionalNetwork.load_from_file
  File "networkconv.pyx", line 223, in nlpnet.network.ConvolutionalNetwork._load_from_file
  File "network.pyx", line 258, in nlpnet.network.Network.padding_left.__set__
TypeError: can't multiply sequence by non-int of type 'float'

```

The test code:
```

import nlpnet
nlpnet.set_data_dir('/home/srl-pt')
tagger = nlpnet.SRLTagger()
tagger.tag(u'O rato roeu a roupa do rei de Roma.')
```

**Comment by erickrf** [comment]
Oops, I only checked the POS tagger in the last commit. It's fixed now for SRL too.

**Comment by biihberduugo** [comment]
Works perfectly!!!! Thanks

**Comment by brendasalenave** [comment]
The same error is occurring when I try to use the SRLTagger.

**Comment by erickrf** [comment]
That is most likely due to an incompatible numpy version. Nlpnet is pretty old now and I haven't updated it to newer packages, so I'd first suggest downgrading numpy.
