### ISSUE TITLE
No such file or directory: '/home/eduardo.pittol/nlpnet-data/prefix-features-pos.npy'

### ISSUE THREAD

**Issue by edpittol** [erickrf/nlpnet#8]
I put in the same dir the content of this two compressed files:
http://nilc.icmc.usp.br/nilc/download/nlpnet-data.zip
http://143.107.183.175:21580/nlpnet/data/pos-pt.tgz

When I call `tagger = nlpnet.POSTagger()`. Show this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/nlpnet/taggers.py", line 170, in __init__
    self._load_data()
  File "/usr/lib64/python2.7/site-packages/nlpnet/taggers.py", line 274, in _load_data
    self.nn = load_network(md)
  File "/usr/lib64/python2.7/site-packages/nlpnet/taggers.py", line 41, in load_network
    prefix_features = utils.load_features_from_file(md.paths[md.prefix_features])
  File "/usr/lib64/python2.7/site-packages/nlpnet/utils.py", line 402, in load_features_from_file
    return np.load(features_file)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 369, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '/home/eduardo.pittol/nlpnet-data/prefix-features-pos.npy'
```

**Comment by erickrf** [comment]
You shouldn't use nlpnet-data.zip, only pos-pt.tgz. Maybe the metadata
files got messed up in the same directory.

2015-02-21 16:27 GMT-02:00 Eduardo Pittol <notifications@github.com>:

**Comment by edpittol** [comment]
I put the nlpnet-data.zip because without it appears this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/nlpnet/taggers.py", line 170, in __init__
    self._load_data()
  File "/usr/lib64/python2.7/site-packages/nlpnet/taggers.py", line 274, in _load_data
    self.nn = load_network(md)
  File "/usr/lib64/python2.7/site-packages/nlpnet/taggers.py", line 34, in load_network
    type_features = utils.load_features_from_file(md.paths[md.type_features])
  File "/usr/lib64/python2.7/site-packages/nlpnet/utils.py", line 402, in load_features_from_file
    return np.load(features_file)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 369, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '/home/eduardo.pittol/nlpnet-data/types-features-pos.npy'
```

And the nlpnet-data.zip has the types-features-pos.npy file.

**Comment by erickrf** [comment]
There must be something wrong. The new nlpnet version doesn't use
types-features-pos.npy, only the .npz file. Make sure you have the latest
version installed.

2015-02-22 19:35 GMT-03:00 Eduardo Pittol <notifications@github.com>:

**Comment by edpittol** [comment]
The version of this repository and PyPI are differents, 1.1.6 (GitHub) and 1.1.5 (PyPI). If I install using PyPI I get the above error. And if I install using a clone of this repository. When I call `import nlpnet`, appear this message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nlpnet/__init__.py", line 3, in <module>
    import taggers
  File "nlpnet/taggers.py", line 17, in <module>
    from network import Network, ConvolutionalNetwork
ImportError: No module named network
```

**Comment by erickrf** [comment]
Yes, the PyPi version is not updated yet. 
The error with the network import was already reported in https://github.com/erickrf/nlpnet/issues/2, I'm trying to fix it. It is hard to test because I've seen it happen sometimes, but not always.
